#!/usr/bin/env node
// Embeds web/index.html and shared/sprites.json (gzipped) into firmware/espgotchi/web_assets.h
// Usage: node tools/gen_web.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "firmware/espgotchi/web_assets.h");

function embed(name, path) {
  const raw = readFileSync(join(root, path));
  const gz = gzipSync(raw, { level: 9 });
  let s = `// ${path}: ${raw.length} bytes -> ${gz.length} bytes gzip\nstatic const uint8_t ${name}[] PROGMEM = {\n`;
  for (let i = 0; i < gz.length; i += 24) s += "  " + Array.from(gz.subarray(i, i + 24)).join(",") + ",\n";
  s += `};\nstatic const size_t ${name}_LEN = ${gz.length};\n\n`;
  console.log(`${path}: ${raw.length} -> ${gz.length} bytes`);
  return s;
}

let h = `// AUTO-GENERATED by tools/gen_web.mjs. Do not edit.\n#pragma once\n#include <stdint.h>\n#include <stddef.h>\n#include <pgmspace.h>\n\n`;
h += embed("WEB_INDEX_GZ", "web/index.html");
h += embed("WEB_SPRITES_GZ", "shared/sprites.json");
// --check: fail instead of writing when the committed file is stale (used by `make check` / CI)
if (process.argv.includes("--check")) {
  const { existsSync } = await import("node:fs");
  if (!existsSync(out) || readFileSync(out, "utf8") !== h) {
    console.error(`${out} is out of date: run \`make gen\` and commit the result`);
    process.exit(1);
  }
  console.log("%s up to date", "web_assets.h");
  process.exit(0);
}
writeFileSync(out, h);
console.log(`wrote ${out}`);
