#!/usr/bin/env node
// Generates firmware/espgotchi/sprites.h from shared/sprites.json.
// Usage: node tools/gen_sprites.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = JSON.parse(readFileSync(join(root, "shared/sprites.json"), "utf8"));
const out = join(root, "firmware/espgotchi/sprites.h");
const LEGACY = { "#": 0, o: 1, x: 2 };

function rgb565(hex) {
  const n = parseInt(hex.replace("#", ""), 16);
  return (((n >> 16) & 0xf8) << 8) | (((n >> 8) & 0xfc) << 3) | ((n & 0xff) >> 3);
}
const hex565 = (c) => "0x" + rgb565(c).toString(16).toUpperCase().padStart(4, "0");

function resolve(name) {
  const spr = src.sprites[name];
  if (!spr) throw new Error(`unknown sprite ${name}`);
  if (spr.rows) return { rows: spr.rows, palette: spr.palette };
  const base = resolve(spr.base);
  const rows = [...base.rows];
  for (const [k, v] of Object.entries(spr.patch)) rows[+k] = v;
  return { rows, palette: spr.palette || base.palette };
}

let h = `// AUTO-GENERATED by tools/gen_sprites.mjs from shared/sprites.json. Do not edit.
#pragma once
#include <stdint.h>

#define SPR_TRANSPARENT 255
#define SPR_PALETTE_MAX 8

struct Sprite {
  const uint8_t *px;  // w*h palette indexes, 255 = transparent
  uint8_t w, h;
  uint16_t palette[SPR_PALETTE_MAX];  // RGB565
};

`;
import { sleepyRows } from "./sleepy.mjs";
// Auto-generate closed-eye sleeping frames for every pet slot
for (const [key, sp] of Object.entries(src.species)) {
  for (const st of ["baby", "child", "teen", "adult", "adult_elite", "adult_feral", "adult_elder"]) {
    const name = `${key}_${st}_0`, { rows, palette } = resolve(name);
    src.sprites[`${key}_${st}_sleep`] = { rows: sleepyRows(rows, sp.eyes || [4, 5]), palette };
  }
}
const names = [];
for (const name of Object.keys(src.sprites)) {
  const { rows, palette } = resolve(name);
  const n = rows.length;
  const px = [];
  rows.forEach((row, i) => {
    if (row.length !== n) throw new Error(`${name}: row ${i} has ${row.length} chars, expected ${n}`);
    for (const c of row) {
      if (c === ".") { px.push(255); continue; }
      const idx = c in LEGACY ? LEGACY[c] : /[0-7]/.test(c) ? +c : -1;
      if (idx < 0 || idx >= palette.length) throw new Error(`${name}: bad char '${c}' row ${i}`);
      px.push(idx);
    }
  });
  const id = name.toUpperCase();
  names.push(id);
  h += `static const uint8_t SPR_${id}_PX[${n * n}] = {\n`;
  for (let r = 0; r < n; r++) h += "  " + px.slice(r * n, r * n + n).join(",") + ",\n";
  const pal = [...palette.map(hex565)];
  while (pal.length < 8) pal.push("0x0000");
  h += `};\nstatic const Sprite SPR_${id} = { SPR_${id}_PX, ${n}, ${n}, { ${pal.join(", ")} } };\n\n`;
}

// Species table: order defines the numeric id used in PetState.species
const species = Object.entries(src.species);
h += `// ---- species ----\n#define SPECIES_COUNT ${species.length}\n#define SPRITE_SLOTS 7  // baby, child, teen, adult, adult_elite, adult_feral, adult_elder\nstruct SpeciesInfo {\n  const char *key;\n  const char *label;\n  uint16_t accent, dayBg, dayBg2, nightBg, nightBg2;\n  const Sprite *egg;\n  const Sprite *frames[SPRITE_SLOTS][2];\n  const Sprite *sleep[SPRITE_SLOTS];\n};\n`;
h += `static const SpeciesInfo SPECIES[SPECIES_COUNT] = {\n`;
for (const [key, s] of species) {
  const K = key.toUpperCase();
  const slots = ["BABY", "CHILD", "TEEN", "ADULT", "ADULT_ELITE", "ADULT_FERAL", "ADULT_ELDER"].map(st => `{ &SPR_${K}_${st}_0, &SPR_${K}_${st}_1 }`).join(", ");
  const sleep = ["BABY", "CHILD", "TEEN", "ADULT", "ADULT_ELITE", "ADULT_FERAL", "ADULT_ELDER"].map(st => `&SPR_${K}_${st}_SLEEP`).join(", ");
  h += `  { "${key}", "${s.label}", ${hex565(s.accent)}, ${hex565(s.bg)}, ${hex565(s.bg2)}, ${hex565(s.night)}, ${hex565(s.night2)}, &SPR_${K}_EGG,\n    { ${slots} }, { ${sleep} } },\n`;
}
h += `};\n`;
// Food item tables (random pick per meal/snack)
const table = (name, list) => `static const Sprite *${name}[${list.length}] = { ${list.map(n => "&SPR_" + n.toUpperCase()).join(", ")} };\nstatic const char *${name}_NAMES[${list.length}] = { ${list.map(n => JSON.stringify(n)).join(", ")} };\n#define ${name}_COUNT ${list.length}\n`;
h += "\n// ---- food ----\n" + table("MEALS", src.meals) + table("SNACKS", src.snacks);
// --check: fail instead of writing when the committed file is stale (used by `make check` / CI)
if (process.argv.includes("--check")) {
  const { existsSync } = await import("node:fs");
  if (!existsSync(out) || readFileSync(out, "utf8") !== h) {
    console.error(`${out} is out of date: run \`make gen\` and commit the result`);
    process.exit(1);
  }
  console.log("%s up to date", "sprites.h");
  process.exit(0);
}
writeFileSync(out, h);
console.log(`wrote sprites.h: ${names.length} sprites, ${species.length} species`);
