#!/usr/bin/env node
// Embeds web/index.html and shared/sprites.json (gzipped) into firmware/espgotchi/web_assets.h
// Usage: node tools/gen_web.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "firmware/espgotchi/web_assets.h");

function embed(name, path) {
  const raw = readFileSync(join(root, path));
  const gz = gzipSync(raw, { level: 9 });
  let s = `// ${path}: ${raw.length} bytes -> ${gz.length} bytes gzip\nstatic const uint8_t ${name}[] PROGMEM = {\n`;
  for (let i = 0; i < gz.length; i += 24) s += "  " + Array.from(gz.subarray(i, i + 24)).join(",") + ",\n";
  s += `};\nstatic const size_t ${name}_LEN = ${gz.length};\n\n`;
  console.log(`${path}: ${raw.length} -> ${gz.length} bytes`);
  return s;
}

let h = `// AUTO-GENERATED by tools/gen_web.mjs. Do not edit.\n#pragma once\n#include <stdint.h>\n#include <stddef.h>\n#include <pgmspace.h>\n\n`;
h += embed("WEB_INDEX_GZ", "web/index.html");
h += embed("WEB_SPRITES_GZ", "shared/sprites.json");
// --check: fail instead of writing when the committed file is stale (used by `make check` / CI).
// Compares the *decompressed* content, not the gzip bytes: different zlib versions (macOS vs the
// Linux runner) produce different streams for the same input, which would make CI red for nothing.
if (process.argv.includes("--check")) {
  const { existsSync } = await import("node:fs");
  const { gunzipSync } = await import("node:zlib");
  const fail = (why) => { console.error(`${out} is out of date (${why}): run \`make gen\` and commit the result`); process.exit(1); };
  if (!existsSync(out)) fail("missing");
  const committed = readFileSync(out, "utf8");
  for (const [name, path] of [["WEB_INDEX_GZ", "web/index.html"], ["WEB_SPRITES_GZ", "shared/sprites.json"]]) {
    const m = committed.match(new RegExp(`static const uint8_t ${name}\\[\\] PROGMEM = \\{([\\d,\\s]*)\\};\\nstatic const size_t ${name}_LEN = (\\d+);`));
    if (!m) fail(`${name} not found`);
    const bytes = Buffer.from(m[1].split(",").map(v => v.trim()).filter(Boolean).map(Number));
    if (bytes.length !== Number(m[2])) fail(`${name} length mismatch`);
    let inflated;
    try { inflated = gunzipSync(bytes); } catch { fail(`${name} is not valid gzip`); }
    if (!inflated.equals(readFileSync(join(root, path)))) fail(`${path} changed`);
  }
  console.log("%s up to date", "web_assets.h");
  process.exit(0);
}
writeFileSync(out, h);
console.log(`wrote ${out}`);
